### PR TITLE
Better seeding for Random (addresses #65)

### PR DESCRIPTION
**Pull request by atifaziz**
This PR addresses #65.

### CODE REVIEW

**Comment by fsateler** [comment]
CI failure appears to be a network outage and thus unrelated.

**Comment by atifaziz** [comment]
> this shared random is then passed directly, which would be unsafe if an async context results in a thread jump

I don't see the issue. If there's a thread jump then the `Random` instance associated with that thread will be used.

**Comment by fsateler** [comment]
>> this shared random is then passed directly, which would be unsafe if an async context results in a thread jump
>
> I don't see the issue. If there's a thread jump then the Random instance associated with that thread will be used.

If `Random` is invoked in thread T1 but the result enumerated in thread T2, then the `ThreadRandom` instance of T1 is used in T2, because `RandomImpl` will capture the passed `Random` instance from T1. 

This change will make it required to enumerate from the same thread that the enumerable was created. Previously, it was only required that the enumerable was only enumerated by a single thread at a time.

**Comment by atifaziz** [comment]
> If `Random` is invoked in thread T1 but the result enumerated in thread T2, then the `ThreadRandom` instance of T1 is used in T2, because `RandomImpl` will capture the passed `Random` instance from T1. 

Oh man, you're totally spot on and good catch! I'm so glad another pair of eyes looked over. Silly me that the very problem I set out to solve ended up rearing its ugly head via the closure. 👹

**Comment by atifaziz** [comment]
@fsateler In 172629953d44b15ddc78f2fdd143ee3893dda048, I've taken another approach. Fortunately, not only is `Random` open to sub-classing but all its `NextXXX` methods are also virtual. I used that to create a singleton implementation that internally uses thread-local `Random` instances. So while the global is still captured, each call into the various `NextXXX` methods uses the `Random` of the thread _at the time of each iteration_.

Let me know what new blunders I've created. 😄

**Comment by fsateler** [comment]
> Fortunately, not only is Random open to sub-classing but all its NextXXX methods are also virtual. I used that to create a singleton implementation that internally uses thread-local Random instances. 

This is avoids this problem. However, by potentially using different `Random` objects while enumerating, the distribution of random numbers might not have the properties expected of a `Random` (uniform distribution is probably the most important). I have no idea how much the distribution could change.

Is this a problem worth worrying about? The conditions under which this problem would arise are not common (constant thread-jumping while enumerating a single sequence).

**Comment by atifaziz** [comment]
> Is this a problem worth worrying about? The conditions under which this problem would arise are not common (constant thread-jumping while enumerating a single sequence).

@fsateler You raise a fair concern but I feel @stephentoub put it best:

> If I really cared about the quality of the numbers, I would use `RNGCryptoServieProvider`.  I’m just trying to escape the hazards of getting back all 0s, or having all of the threads seeing the exact same numbers.  This is a fair compromise if the statistical properties beyond that aren’t that important.

**Comment by fsateler** [comment]
@atifaziz Right, I agree for most users this will not be an issue. Maybe it is only necessary to add a remark to the documentation for the relevant overloads?

**Comment by atifaziz** [comment]
@fsateler What do you think of this?

```c#
        /// <remarks>
        /// The implementation internally uses a thread-local instance of
        /// <see cref="System.Random" /> to generate a random number on each
        /// iteration. The actual <see cref="System.Random" /> instance used
        /// therefore will depend on the thread on which a single iteration is
        /// taking place; that is the call to
        /// <see cref="System.Collections.IEnumerator.MoveNext()" />. If the
        /// overall iteration takes place on different threads (e.g.
        /// asynchronous await completing on different threads) then various
        /// different <see cref="System.Random" /> instances will be involved
        /// in the generation of the sequence of random numbers.
        /// </remarks>
```

**Comment by fsateler** [comment]
@atifaziz Looks good to me, modulo a minor nit. I'd also note that the thread-local instance is shared among enumerables in the same thread:

```csharp
        /// <remarks>
        /// The implementation internally uses a shared, thread-local instance of
        /// <see cref="System.Random" /> to generate a random number on each
        /// iteration. The actual <see cref="System.Random" /> instance used
        /// therefore will depend on the thread on which a single iteration is
        /// taking place; that is the call to
        /// <see cref="System.Collections.IEnumerator.MoveNext()" />. If the
        /// overall iteration takes place on different threads (e.g.
        /// via asynchronous awaits completing on different threads) then various
        /// different <see cref="System.Random" /> instances will be involved
        /// in the generation of the sequence of random numbers. Because the
        /// <see cref="System.Random" /> instance is shared, if multiple sequences
        /// are generated in the same thread, the order of enumeration affects the
        /// resulting sequences.
        /// </remarks>
```

**Pull request merged**
