### PR TITLE
Add test for Exclude, Lag, Lead and SkipUntil that use TestingSequences

### LINKED ISSUE #649: Missing using instruction in Exclude and Lead
Here the list of not disposed enumerators
Unit test should be added for it (maybe we can do a generic test like NullArgumentTest).

- [x] MoreLinq\Exclude.cs:48
- [x] MoreLinq\Lead.cs:68
~SkipUntil~

We should have test for them

### PR DESCRIPTION
**Pull request by Orace**
Fix #649

### CODE REVIEW

**Comment by Orace** [comment]
78322c2 fix #664

**Comment by Orace** [comment]
7414473  Fix #665

**Comment by atifaziz** [comment]
Thanks for those tests and fixes but this PR is too big. Can you please break it up into the four separate fixes (for `Exclude`, `Lag`, `Lead` and `SkipUntil`) that it is, even if the fix is logically the same?

**Comment by Orace** [comment]
Exclude call to MoveNext after sequence end is fixed here #692

**Pull request closed without merging**
