### PR TITLE
Fix documentation (issue #254)

### PR DESCRIPTION
**Pull request by leandromoh**
Added `<typeparam name="T"/>` for `SkipLast` .

I also added some operator that was missing on `project.json`:

- AtLeast
- AtMost
- CountBetween
- Exactly
- FallbackIfEmpty
- FullGroupJoin

### CODE REVIEW

**Comment by atifaziz** [comment]
Thanks for spotting those missing operators and adding them. :+1: For next time, though, would be best to open separate PR for unrelated issues.

**Comment by atifaziz** [comment]
Closed as 0bdb7bb3e078d1f54f10095f2cd345f4d20a10cd and 0bdb7bb3e078d1f54f10095f2cd345f4d20a10cd

**Comment by leandromoh** [comment]
>  For next time, though, would be best to open separate PR for unrelated issues.

@atifaziz thanks for the tip. when do you plan to see the aggregateright and memoize PR?

**Comment by atifaziz** [comment]
@leandromoh I've moved `AggregateRight` to the [next release](https://github.com/morelinq/MoreLINQ/milestone/4) because I figured I won't get time before end of the month to review it. I'm trying to keep to a schedule of a release per month and would rather delay features than releases. As for `Memoize`, last I recall I felt that Ix already gave us that so was hesitant to add it to MoreLinq; unless of course #214 is closed via #235.

**Comment by leandromoh** [comment]
@atifaziz I understood. I also would like to see `Memoize`, `Tranpose` and `UnAggregate` in the next release. Do you think it is possible? As for `Memoize`, we can simple rename it to `Cache` to avoid conflict, as you already suggested.

**Comment by atifaziz** [comment]
> I also would like to see `Memoize`, `Tranpose` and `UnAggregate` in the next release. Do you think it is possible?

We can certainly try provided we've already agreed on adding them. Review takes time so what would help to speed up thing is to up the quality of the PRs using feedback we've been over in past PRs.

> As for `Memoize`, we can simple rename it to `Cache` to avoid conflict, as you already suggested.

This belong with #211.

**Comment by leandromoh** [comment]
> Review takes time so what would help to speed up thing is to up the quality of the PRs using feedback we've been over in past PRs.

Of course, MoreLinq was the first project I contributed and I learnt a lot of things with the reviews:

implementations:

1. bank line between XML documentation and method for clarity
2. exception/documentation descriptions always end with full-stop or period
3. avoid enumerating twice non-list collections
4. xxxImpl method don't must be an extension method
5. quote all params on summary 
6. use var where type is explicit
7. descritive variable names always
8. check comparer.GetHashCode before comparer.Equals
9. using statements go inside the namespace block

tests:

1. non-extension invocation style when testing if source is null
2. use TestCase more appropriately
3. alignment test cases when it has many parameters for clarity
4. no use random data on tests
5. no "xxxSimpleTest"
6. use  sequence equality assertion
7. give a different name for each overload on tests
8. Test methods don't need to end in the Test suffix
9. act-arrange-assert pattern when necessary

**Comment by atifaziz** [comment]
> MoreLinq was the first project I contributed and I learnt a lot of things

You're doing well and thanks for all your contributions so far! :+1: Keep it up! I'm also really glad to see that you've taken note of all the feedback as it'll help to avoid repeating ourselves.

**Pull request closed without merging**
