### PR TITLE
Hide `ToDictionary()` in net8+

### LINKED ISSUE #1012: Hide `ToDictionary()` in net8+
net8.0 has added `ToDictionary()` overloads that overlap the MoreLinq versions. We should hide them in net8+. Similar to #749.

See: https://github.com/dotnet/runtime/pull/85811

### PR DESCRIPTION
**Pull request by viceroypenguin**
This PR updates `ToDictionary()` to be hidden on net8, since the BCL has added a duplicate method.

Fixes #1012
Relates to #945

### CODE REVIEW

**Review by atifaziz — CHANGES_REQUESTED** [review]
Now that #1041 is merged with 9a4ea61b5b5b15c7695bd846695a5a9aa84cf8f1, can we resolve the conflicts so there's a smaller diff to review? Thanks!

**Comment by viceroypenguin** [comment]
> Now that #1041 is merged with [9a4ea61](https://github.com/morelinq/MoreLINQ/commit/9a4ea61b5b5b15c7695bd846695a5a9aa84cf8f1), can we resolve the conflicts so there's a smaller diff to review? Thanks!

Done!

**Review by atifaziz — CHANGES_REQUESTED** [review]
> Done!

Thanks, though the [build is broken](https://ci.appveyor.com/project/raboof/morelinq/builds/48544620). Could you have a look?

**Review by atifaziz — APPROVED** [review]
Thanks for your help with this!

---
PS I reverted some unrelated formatting changes with c9144e4c4cc20a3185ac80a6134ea8dfae1857f6, but I would appreciate it if you can avoid them in the first place in your PRs; it really helps with reducing the review time. Thanks.

**Pull request merged**
