### PR TITLE
Replace null-forgiving operator uses with debug assertions

### PR DESCRIPTION
**Pull request by atifaziz**
This PR introduces `Debug.Assert` that's defined similarly to [`System.Diagnostics.Debug.Assert`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=net-7.0#system-diagnostics-debug-assert(system-boolean-system-string)) to help eliminate the bulk uses of the null-forgiving operator (`!`). The assertion more explicitly states the illegal case, and if triggered, will also relay the offending condition in the message. It also eliminates needing to suppress [CS8602](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-dereference-of-null) and [CS8603](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference) in target earlier than .NET 6.

This PR also adds `Assume.NotNull`, that's a `Debug.Assert` in disguise, but which specifically asserts the not-null-reference case. The idea is to make these cases easily searchable in code.

### CODE REVIEW

**Comment by viceroypenguin** [comment]
While I am not opposed to `Debug.Assert(bool condition)`, I would _suggest_ adding a `static T AssertNotNull<T>([NotNull, AllowNull] T? object) where T : class`, which receives an object, throws if null, and returns the object unchanged otherwise. The nullability analyzer will treat the returned object as not-null, which means it can be used immediately.

Example use case:
```csharp
var g = Debug.AssertNotNull(_lastGrouping);
```

**Comment by atifaziz** [comment]
> While I am not opposed to `Debug.Assert(bool condition)`, I would _suggest_ adding a `static T AssertNotNull<T>([NotNull, AllowNull] T? object) where T : class`, which receives an object, throws if null, and returns the object unchanged otherwise. The nullability analyzer will treat the returned object as not-null, which means it can be used immediately.
> 
> Example use case:
> 
> ```cs
> var g = Debug.AssertNotNull(_lastGrouping);
> ```

You can't do that because such assertion methods are _conditional methods_ that get compiled out of release builds and therefore they must return `void`. See also the [remarks section of the `ConditionalAttribute` docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=net-7.0#remarks):

> Applying [ConditionalAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=net-7.0) to a method indicates to compilers that a call to the method should not be compiled into Microsoft intermediate language (MSIL) unless the conditional compilation symbol that is associated with [ConditionalAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=net-7.0) is defined. _You will get a compilation error in Visual Studio if you apply this attribute to a method that does not return void.

**Comment by viceroypenguin** [comment]
Ah, I missed the `[Conditional]`. I'll ponder this further.

**Comment by atifaziz** [comment]
> which receives an object, throws if null, and returns the object unchanged otherwise

I've added this idea with 7e6fa33d1ea58325480998943cbfcf8cb9ca9a33 and updated the [initial description](https://github.com/morelinq/MoreLINQ/pull/890#issue-1450492936) with:

> This PR also adds `Assume.NotNull`, that's a `Debug.Assert` in disguise, but which specifically asserts the not-null-reference case. The idea is to make these cases easily searchable in code.

**Comment by viceroypenguin** [comment]
Finished product LGTM

**Pull request merged**
