### PR TITLE
Exclude: Add test, fix implementation

### PR DESCRIPTION
**Pull request by Orace**
Fix a part of #649
Fork of #660

### CODE REVIEW

**Comment by Orace** [comment]
For the headers, I opened #671

**Comment by Orace** [comment]
Closed. The implementation of Exclude is fixed here #672

**Comment by Orace** [comment]
Exclude call to MoveNext after sequence end is fixed here #692

**Comment by atifaziz** [comment]
Thank you for the splits!

**Comment by Orace** [comment]
[You are welcome.](https://youtu.be/M7FIvfx5J10)

**Pull request closed without merging**
