### PR TITLE
Simplify `EquiZip` implementation

### PR DESCRIPTION
**Pull request by viceroypenguin**
The various Zip* methods currently share implementation in `.ZipImpl()`. However, the code is simpler for each one when they are written separately; that is, in this case, the variances are more than the commonality. As such, we should allow each method to be implemented separately.

This PR updates the implementation of `EquiZip` to be done separately from `.ZipImpl()`.

### CODE REVIEW

**Comment by viceroypenguin** [comment]
NB: This may be a v4.0.0 PR?

**Comment by atifaziz** [comment]
Possibly a duplicate of PR #715 by @Orace?

**Comment by viceroypenguin** [comment]
Duplicate in the sense that both separate the implementations of the three zip functions, yes. However, #715 uses T4 to generate separate implementations of each method for argument count 2-4. Also, #715 and #902 have very different implementations. IMO #902 is simpler, because the control flow is more linear, rather than 4-way branch with multiple exit points.

**Comment by Orace** [comment]
Some thoughts about this:
 - The used pattern probably wastes resources. It's implemented for 4 sources, and for other cases, it uses dummy sources and discards values with a lambda (resulting to memory allocation that can be avoided): https://github.com/morelinq/MoreLINQ/blob/5ff2ad4ea88cc2052eded807d87a421b9a301ba6/MoreLinq/EquiZip.cs#L71
   It will not scale well if we want to add overloads with more sources.
   
 - The control flow of #715 can be simplified a little bit to match #902 that offers more complete exception messages.

**Comment by viceroypenguin** [comment]
@Orace Here's a copy of the [code gen](https://github.com/viceroypenguin/SuperLinq/blob/master/Generators/SuperLinq.Generator/EquiZip.sbntxt#L66-L96) for a simpler control flow if you want to steal it.

Closing this PR in favor of an updated #715.

**Pull request closed without merging**
