### PR TITLE
Avoid multiple enumerations on Repeat and Cartesian operators

### PR DESCRIPTION
**Pull request by leandromoh**

### CODE REVIEW

**Comment by leandromoh** [comment]
@atifaziz How about this? Since memoize is internal, we can change the approach if something better appears latter, without any breaking-change.

**Comment by leandromoh** [comment]
@atifaziz how about this?

**Comment by atifaziz** [comment]
> I would like to review this after merging #211 and use that `Memoize` implementation here. 

Done! 🙌

**Comment by atifaziz** [comment]
This needs to be two separate PRs, one for `Catersian` and another for `Repeat`, especially now that `Memoize` is in.

**Comment by atifaziz** [comment]
@leandromoh I have submitted a PR for `Cartesian` (see #490). Unless you see an issue with it, perhaps you'd like to address #489 in a similar way?

**Pull request closed without merging**
