### PR TITLE
Improve Window tests

### PR DESCRIPTION
**Pull request by Orace**
This PR address #654

### CODE REVIEW

**Comment by Orace** [comment]
Doing TDD here, 8e179ad contains the new failing tests

**Comment by atifaziz** [comment]
Closing this as #652 isn't a bug that needs fixing. The yielded windows can be modified to the caller's desire. The test just shows that and nothing more.

**Comment by Orace** [comment]
This PR now address #654, @atifaziz, can you please reopen it.

**Comment by Orace** [comment]
> 
> 
> Closing this as #652 isn't a bug that needs fixing. The yielded windows can be modified to the caller's desire. The test just shows that and nothing more.

The test actually show that modification in one window is transmitted to the next one.

**Pull request closed without merging**
