### PR TITLE
Batch with lazy enumerables (issue #400)

### PR DESCRIPTION
**Pull request by leandromoh**
implements the requested of [Optimize Batch to return lazy enumerables](https://github.com/morelinq/MoreLINQ/issues/400).  

As requested [here](https://github.com/morelinq/MoreLINQ/issues/400#issuecomment-370135245), all batches are buffered in different lists. So when you move on to the next batch, the one before becomes fodder for GC.

### CODE REVIEW

**Comment by leandromoh** [comment]
@atifaziz @arithmomaniac
What do you think?

**Comment by Arithmomaniac** [comment]
I have my hands full, so unless @atifaziz asks me to do otherwise, I'm not going to review this.

**Comment by atifaziz** [comment]
@Arithmomaniac I've got my hand full here too so I doubted I'll get round to reviewing this any time soon. There's another reason…we never decided in #400 that there is indeed a problem that needs and what the solution would be so this PR jumps the gun for me. If @leandromoh is just sharing an experimenting with an implementation here then that's okay but this isn't going to be a priority for me.

@Arithmomaniac Perhaps #400 should be closed seeing that no one has the time and that `Batch` isn't burning down the house for anymore? 😉

**Comment by Arithmomaniac** [comment]
@atifaziz I'm fine with this, but we should [have a tag for things that were closed due to lack of interest](https://github.com/moq/moq4/issues/505#issuecomment-354365114) if we don't already.

**Comment by atifaziz** [comment]
@Arithmomaniac There's already [the won't-fix label][wontfix] for that but honestly, a closed issue that's not been tagged as either an [enhancement][enhancement], a [bug][bug] or a [task][task] is essentially something that's been abandoned. Perhaps won't-fix is too strong for #400 as I feel it doesn't have a problem statement?

[wontfix]: https://github.com/morelinq/MoreLINQ/issues?q=label%3Awontfix
[enhancement]: https://github.com/morelinq/MoreLINQ/issues?q=label%3Aenhancement
[bug]: https://github.com/morelinq/MoreLINQ/issues?q=label%3Abug
[task]: https://github.com/morelinq/MoreLINQ/issues?q=label%3Atask

**Comment by Arithmomaniac** [comment]
Maybe "won't-implement"?

**Comment by leandromoh** [comment]
I cant see why close the issue If It was not resolved.  

There is a lot of issues openned even without a PR. So why close this, that does?

**Comment by atifaziz** [comment]
Closing since #400 has been closed too.

**Pull request closed without merging**
