### PR TITLE
Add missing documentation for Repeat and ZipShortest method. #148 #149

### PR DESCRIPTION
**Pull request by VladimirRybalko**
I've added some missing xml documentation as required in #148 and #149.

### CODE REVIEW

**Comment by atifaziz** [comment]
@VladimirRybalko Thanks! Could you just split that into two individual commits, one addressing #148 and the other #149? The commit message for each can then be borrowed from the corresponding issue title.

**Comment by VladimirRybalko** [comment]
@atifaziz done.

**Comment by atifaziz** [comment]
Merged & thanks thought I left out the original single commit (VladimirRybalko/MoreLINQ@c2c41b2b2aec7bbbfca9abd86f950f5fdb467b30) and the blank merge (VladimirRybalko/MoreLINQ@b4f524d3a780333e845accb60cb9bf6f5c61076e) as they were unnecessary.

**Comment by atifaziz** [comment]
Published in morelinq/morelinq.github.io@2fc359dbe29935ca02a23337e29812a113c24155

**Pull request closed without merging**
